//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int IdPrestamo { get; set; }
        public System.DateTime Fecha_Prestamo { get; set; }
        public System.DateTime Fecha_Devolucion { get; set; }
        public int IdLibro { get; set; }
        public int IdUsuario { get; set; }
        public int IdEmpleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Libros Libros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
